# fly.toml app configuration file generated for caesaraimusicstreamyt-still-bush-4772 on 2024-12-22T21:26:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'caesaraimusicstreamyt-still-bush-4772'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
